### ISSUE TITLE
Confusion between "play" and the "next" button

### ISSUE THREAD

**Issue by gpoesia** [gpoesia/loopye#31]
I've observed this with two children: when they forget what each button means, they often click the wrong one. We should probably differentiate them in some way.

**Comment by nildo** [comment]
I actually have a suggestion: change the place where the buttons are. The "play" button could be below the box where they write the program. This placement would reinforce the idea that "I am running the code I just wrote". And the "next" button could be on the right of the screen.

**Comment by msclar** [comment]
I tried putting the "play" button below the box where they write the program, but I think it is kind of hard to find. 

![screenshot from 2016-09-30 01-08-32](https://cloud.githubusercontent.com/assets/8364317/18980426/93b3fc2a-86aa-11e6-84a2-e21c44860fc2.png)

Maybe it would be more vieweable on top of the box, or inside of it, to the upper right corner (this last one I wasn't able to code yet, but I think it would look nicer).

![screenshot from 2016-09-30 01-11-42](https://cloud.githubusercontent.com/assets/8364317/18980455/e168dc74-86aa-11e6-8087-46a7d2d62cfb.png)

What do you think? Which option would be the best?
If none of them are convincing, maybe I could add a small text below each symbol (in Portuguese, of course) to remind the players of the function of each button.

**Comment by gpoesia** [comment]
I think the second placement is better. @nildo?

**Comment by gpoesia** [comment]
After all the changes to the environment in general and specifically to the layout, this doesn't seem to be a problem anymore. Closing for now.
