### ISSUE TITLE
Robot takes too long to finish executing some levels

### ISSUE THREAD

**Issue by gpoesia** [gpoesia/loopye#38]
Especially in lesson 3, the robot can take very long (sometimes more than 3 minutes) to execute a single step.

As discussed offline, a fix would be to add a button that speeds-up the animation (say, by 8x). Then, the player can watch in normal speed until some point (e.g. until she checks correctness in the first iterations of a long loop), and then skip the rest.

The implementation for this would involve adding a new state variable to the animator, storing the time at which the speed-up started (if it did at all). Then, time after that point is counted as multiplied by some factor. This would need to be integrated with the UI: another button would be added to the ButtonBar, which should trigger the action of setting the speed-up beginning in the animator (if it's not already set).

**Comment by msclar** [comment]
I'm working on this! I was already able to see the speed up manually, but there is still some work to do.
